language: generic
os: linux
dist: bionic

addons:
  apt:
    packages:
    - pcscd
    - pcsc-tools
    - libpcsclite-dev
    - docbook-xsl
    - xsltproc
    - help2man
    - ant
    - socat
    - yubico-piv-tool
    - opensc
    - gcc
    - openjdk-8-jdk

before_script:
  - set -ex;

    sudo update-java-alternatives -s java-1.8.0-openjdk-amd64;
    sudo update-alternatives --get-selections | grep ^java;
    export PATH="/usr/lib/jvm/java-8-openjdk-amd64/bin/:$PATH";
    export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/;
    env | grep -i openjdk;

    git clone https://github.com/frankmorgner/vsmartcard.git;
    cd vsmartcard/virtualsmartcard;
    autoreconf -vis && ./configure && sudo make install;
    cd $TRAVIS_BUILD_DIR;
    sudo /etc/init.d/pcscd restart;

    git clone https://github.com/martinpaljak/oracle_javacard_sdks.git;
    export JC_SDKS=$PWD/oracle_javacard_sdks;
    export JC_HOME=$JC_SDKS/jc305u3_kit;
    export JC_CLASSIC_HOME=$JC_HOME;

    git clone https://github.com/arekinath/jcardsim.git;
    cd jcardsim;
    mvn initialize && mvn clean install -DskipTests;
    cd $TRAVIS_BUILD_DIR;

    export JC_HOME=$JC_SDKS/jc304_kit;
    ant dist;

    sudo wget https://github.com/arekinath/pivy/releases/download/v0.5.1/pivy_0.5.1-1_bionic_amd64.deb;
    sudo dpkg -i pivy_0.5.1-1_bionic_amd64.deb;

    gem install minitest;

    set +ex;

script:
  - set -ex;

    sudo systemctl stop pcscd.service pcscd.socket;
    sudo /usr/sbin/pcscd -f &
    PCSCD_PID=$!;

    java -noverify -cp bin/:jcardsim/target/jcardsim-3.0.5-SNAPSHOT.jar com.licel.jcardsim.remote.VSmartCard test/jcardsim.cfg >/dev/null &
    PID=$!;
    sleep 5;
    opensc-tool --card-driver default --send-apdu 80b80000120ba000000308000010000100050000020F0F7f;
    opensc-tool -n;

    ./test/simulator-tests 'Virtual PCD 00 00';

    kill -9 $PID;

    sudo kill -9 $PCSCD_PID;

    set +ex;
